### ISSUE TITLE
在线文档 2.4.2 节中的文字错误

### ISSUE THREAD

**Issue by hrjtju** [datawhalechina/grape-book#10]
![image](https://github.com/datawhalechina/grape-book/assets/93460182/cd909f46-d94a-472c-9cd3-13d006f041cc)

高亮部分应该为 “关联矩阵” 而不是 “邻接矩阵”

此问题由 id：北极熊 的学习者发现。

**Comment by xinqi-fan** [comment]
已经修改。感谢学习者北极熊！期待更多反馈
