### ISSUE TITLE
关于差集的 notaion 问题

### ISSUE THREAD

**Issue by hrjtju** [datawhalechina/grape-book#14]
<img width="1213" alt="image" src="https://github.com/datawhalechina/grape-book/assets/93460182/f83f5a8d-c780-4dcc-8f97-30b703ef9653">

在线教程的2.3.5节中的差集应使用反斜杠： $V \setminus V'$ （`V \setminus V'`）或减号： $V - V'$ （`V - V'`），而不是斜杠`/`。
斜杠`/`在数学中常用来表示商集，如集合 $A$ 在等价关系 $\sim$ 下的商集 $V/_{\sim}$ .

**Comment by xinqi-fan** [comment]
感谢 希望提出更多修改建议！
